"""public share links and sessions

Revision ID: 5ce6e701130b
Revises: cbb7fc9dd920
Create Date: 2026-08-13 12:22:46.157815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ce6e701130b'
down_revision: Union[str, Sequence[str], None] = 'cbb7fc9dd920'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('public_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('persona_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['persona_id'], ['personas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_public_sessions_persona_id'), 'public_sessions', ['persona_id'], unique=False)
    op.add_column('chat_messages', sa.Column('session_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_chat_messages_session_id'), 'chat_messages', ['session_id'], unique=False)
    op.create_foreign_key(None, 'chat_messages', 'public_sessions', ['session_id'], ['id'], ondelete='CASCADE')
    op.add_column('personas', sa.Column('share_token', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_personas_share_token'), 'personas', ['share_token'], unique=True)
    op.add_column('scheduled_calls', sa.Column('session_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_scheduled_calls_session_id'), 'scheduled_calls', ['session_id'], unique=False)
    op.create_foreign_key(None, 'scheduled_calls', 'public_sessions', ['session_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'scheduled_calls', type_='foreignkey')
    op.drop_index(op.f('ix_scheduled_calls_session_id'), table_name='scheduled_calls')
    op.drop_column('scheduled_calls', 'session_id')
    op.drop_index(op.f('ix_personas_share_token'), table_name='personas')
    op.drop_column('personas', 'share_token')
    op.drop_constraint(None, 'chat_messages', type_='foreignkey')
    op.drop_index(op.f('ix_chat_messages_session_id'), table_name='chat_messages')
    op.drop_column('chat_messages', 'session_id')
    op.drop_index(op.f('ix_public_sessions_persona_id'), table_name='public_sessions')
    op.drop_table('public_sessions')
    # ### end Alembic commands ###
