"""chat_messages seq identity

Revision ID: 657aabd913fa
Revises: 730b1d235ea7
Create Date: 2026-08-12 20:04:13.825558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '657aabd913fa'
down_revision: Union[str, Sequence[str], None] = '730b1d235ea7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # autogenerate doesn't detect plain-column -> IDENTITY changes; written
    # by hand. seq had no DB-side sequence at all (a modeling bug — it's
    # not the table's PK, so SQLAlchemy's autoincrement=True never applied
    # server-side), so every insert 400'd on a NOT NULL violation.
    op.execute("ALTER TABLE chat_messages ALTER COLUMN seq ADD GENERATED BY DEFAULT AS IDENTITY")


def downgrade() -> None:
    op.execute("ALTER TABLE chat_messages ALTER COLUMN seq DROP IDENTITY IF EXISTS")
