"""soft delete columns

Revision ID: cbb7fc9dd920
Revises: 657aabd913fa
Create Date: 2026-08-13 09:03:40.258389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbb7fc9dd920'
down_revision: Union[str, Sequence[str], None] = '657aabd913fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('personas', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tool_instances', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tool_instances', 'deleted_at')
    op.drop_column('personas', 'deleted_at')
    # ### end Alembic commands ###
